export const APP_VERSION = '1.4.0'
export const APP_NAME = '가림 암기노트'
export const SUPPORT_EMAIL = 'clowood.dev@gmail.com'
export const PRIVACY_URL = 'https://app-garim.pages.dev/privacy.html'
export const SUPPORT_URL = 'https://app-garim.pages.dev/support.html'
export const SAMPLE_PDF_NAME = '샘플-암기연습.pdf'
